name: CD
on:
  repository_dispatch:
    types: [Model is registered]
    
jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest

    steps:    
    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        ref: eedorenko/cd
    - name: Handle Deploy Event
      id: deh
      run: |
        python3 actions_utils/event_dispatcher.py "deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.SERVICE_PRINCIPAL }}", "clientSecret":"${{ secrets.SERVICE_PRINCIPAL_PWD }}", "subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.TENANT }}"}' 
    - name: Deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |          
          $GITHUB_WORKSPACE/code/deploy/deploy.sh -m tacosandburritos \
                                                  -u ${{ secrets.SUBSCRIPTION_ID }} \
                                                  -r ${{ secrets.RESOURCE_GROUP }} \
                                                  -w ${{ secrets.AML_WORKSPACE }} \
                                                  -x ${{ steps.deh.outputs.RUN_ID }} \
                                                  -d mexicanfood


      
