name: CD
on:
  repository_dispatch:
    types: [Model is registered]
    
jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.SERVICE_PRINCIPAL }}", "clientSecret":"${{ secrets.SERVICE_PRINCIPAL_PWD }}", "subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.TENANT }}"}' 
    - name: Deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |          
          $GITHUB_WORKSPACE/code/deploy/deploy.sh -m tacosandburritos \
                                                  -u ${{ secrets.SUBSCRIPTION_ID }} \
                                                  -r ${{ secrets.RESOURCE_GROUP }} \
                                                  -w ${{ secrets.AML_WORKSPACE }} \
                                                  -x 1 \
                                                  -d mexicanfood


      
