name: Receive Repository Dispatch Payload
on: repository_dispatch

jobs:
  process-repository-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
    
    - name: Handle Repo Dispatch Payload
      id: rd
      run: |
        python3 events/event_dispatcher.py --event_type "${{ github.event.action }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KFP_DSHB: ${{ secrets.KFP_DSHB }}
